import type {
  OlosConformanceCoverageStatus,
  OlosConformanceLevel,
} from "./coverage-types";

export type OlosConformanceCoverageRow = readonly [
  id: string,
  level: OlosConformanceLevel,
  testFile: string,
  section: string | null,
  status?: OlosConformanceCoverageStatus,
];

export const OLOS_CONFORMANCE_COVERAGE_ROWS = [
  ["CORE-STORE-001", "core", "src/conformance.test.ts", null],
  ["CORE-STORE-002", "core", "src/conformance.test.ts", null],
  ["CORE-STORE-003", "core", "src/conformance.test.ts", null],
  ["CORE-STORE-004", "core", "src/conformance.test.ts", null],
  ["CORE-STORE-005", "core", "src/conformance.test.ts", null],
  ["CORE-STORE-006", "core", "src/protocol/serialized-store.test.ts", null],
  ["CORE-STORE-007", "core", "src/protocol/serialized-store.test.ts", null],
  ["CORE-STORE-008", "core", "src/protocol/sqlite-store.test.ts", null],
  ["CORE-SCHEMA-001", "core", "src/schema.test.ts", "3.1"],
  ["CORE-SLOT-001", "core", "src/state/upload-slot.test.ts", "4.2"],
  ["CORE-SLOT-002", "core", "src/state/upload-slot.test.ts", "4.2"],
  ["CORE-SLOT-003", "core", "src/state/commit.test.ts", "4.5.1"],
  ["CORE-SLOT-004", "core", "src/state/upload-slot.test.ts", "4.3"],
  ["CORE-SLOT-005", "core", "src/state/upload-slot.test.ts", "4.3"],
  ["CORE-SLOT-006", "core", "src/protocol/coordinator.test.ts", "4.2"],
  ["CORE-SLOT-007", "core", "src/protocol/coordinator.test.ts", "4.8"],
  ["CORE-COMMIT-001", "core", "src/state/commit.test.ts", "4.5.1"],
  ["CORE-COMMIT-002", "core", "src/state/commit.test.ts", "4.5.1"],
  ["CORE-COMMIT-003", "core", "src/state/commit.test.ts", "4.5.1"],
  ["CORE-COMMIT-004", "core", "src/state/commit.test.ts", "4.5.1"],
  ["CORE-COMMIT-005", "core", "src/state/commit.test.ts", "4.5.1"],
  ["CORE-COMMIT-006", "core", "src/state/commit.test.ts", "4.5.2"],
  ["CORE-COMMIT-007", "core", "src/state/commit.test.ts", "4.5.2"],
  ["CORE-COMMIT-008", "core", "src/state/committed-window.test.ts", "5.4"],
  ["CORE-LATE-001", "core", "src/state/commit.test.ts", "4.5.3"],
  ["CORE-LATE-002", "core", "src/state/commit.test.ts", "4.5.3"],
  ["CORE-EVENT-001", "core", "src/state/observed-upload.test.ts", "4.4"],
  ["CORE-EVENT-002", "core", "src/state/observed-upload.test.ts", "4.4"],
  ["CORE-EVENT-003", "core", "src/state/observed-upload.test.ts", "4.4"],
  ["CORE-EVENT-004", "core", "src/state/observed-upload.test.ts", "4.4"],
  ["CORE-EVENT-005", "core", "src/state/observed-upload.test.ts", "4.4"],
  ["CORE-WINDOW-001", "core", "src/state/cursor.test.ts", "4.7"],
  ["CORE-WINDOW-002", "core", "src/hls/media-playlist.test.ts", null],
  ["CORE-WINDOW-003", "core", "src/validation/committed-window.test.ts", "5.1"],
  ["CORE-WINDOW-004", "core", "src/validation/committed-window.test.ts", "5.1"],
  ["CORE-WINDOW-005", "core", "src/validation/committed-window.test.ts", "5.1"],
  ["CORE-WINDOW-006", "core", "src/hls/media-playlist.test.ts", null],
  ["CORE-WINDOW-007", "core", "src/state/committed-window.test.ts", "5.2"],
  ["CORE-RUNTIME-001", "runtime", "e2e/runtime-pipeline.test.ts", "6"],
  ["CORE-RUNTIME-002", "runtime", "e2e/runtime-pipeline.test.ts", "6"],
  ["CORE-RUNTIME-003", "runtime", "e2e/runtime-pipeline.test.ts", "6"],
  ["CORE-RUNTIME-004", "runtime", "src/runtime/http.test.ts", "6"],
  ["CORE-RUNTIME-005", "runtime", "src/runtime/http.test.ts", "6"],
  ["CORE-RUNTIME-006", "runtime", "src/runtime/retention.test.ts", "9.2"],
  ["CORE-RUNTIME-007", "runtime", "src/runtime/publisher.test.ts", null],
  [
    "CORE-RUNTIME-008",
    "runtime",
    "src/runtime/publisher-lease.test.ts",
    "6.4.3",
  ],
  ["CORE-RUNTIME-009", "runtime", "src/runtime/publisher-plan.test.ts", null],
  ["CORE-RUNTIME-010", "runtime", "src/runtime/publisher-expiry.test.ts", null],
  ["CORE-RUNTIME-011", "runtime", "src/runtime/health.test.ts", "6.4.4"],
  ["CORE-RUNTIME-012", "runtime", "src/media/latency-profile.test.ts", null],
  [
    "CORE-RUNTIME-013",
    "runtime",
    "src/runtime/publisher-cadence.test.ts",
    null,
  ],
  [
    "CORE-RUNTIME-014",
    "runtime",
    "src/runtime/publisher-cadence.test.ts",
    null,
  ],
  ["CORE-RUNTIME-015", "runtime", "src/runtime/publisher.test.ts", null],
  ["CORE-RUNTIME-016", "runtime", "src/runtime/session.test.ts", "6.4"],
  ["CORE-RUNTIME-017", "runtime", "src/runtime/http.test.ts", "6"],
  ["CORE-RUNTIME-018", "runtime", "src/runtime/client.test.ts", null],
  ["CORE-RUNTIME-019", "runtime", "e2e/runtime-client-flow.test.ts", null],
  ["CORE-RUNTIME-020", "runtime", "src/runtime/slot.test.ts", "6.5.1"],
  ["CORE-RUNTIME-021", "runtime", "src/runtime/commit.test.ts", "6.5.2"],
  ["CORE-RUNTIME-022", "runtime", "src/runtime/http.test.ts", "6.7"],
  ["CORE-RUNTIME-023", "runtime", "src/runtime/http.test.ts", "6.7"],
  ["CORE-RUNTIME-024", "runtime", "src/runtime/http.test.ts", "6.7"],
  ["CORE-RUNTIME-025", "runtime", "src/runtime/response.test.ts", "6.3"],
  ["OBJ-LAYOUT-001", "object", "src/runtime/publisher-plan.test.ts", "7.5"],
  ["OBJ-GRANT-001", "object", "src/s3/upload-grant.test.ts", "7.2"],
  ["OBJ-GRANT-002", "object", "src/s3/upload-grant.test.ts", "7.2"],
  ["OBJ-GRANT-003", "object", "src/s3/coordinator.test.ts", "7.2"],
  [
    "OBJ-GRANT-004",
    "object",
    "src/state/provider-upload-grant-policy.test.ts",
    "7.7",
  ],
  [
    "OBJ-GRANT-005",
    "object",
    "src/state/provider-upload-grant-policy.test.ts",
    "7.7",
  ],
  ["OBJ-HEAD-001", "object", "src/state/observed-upload.test.ts", "7.3"],
  ["OBJ-PUB-001", "object", "src/state/publication.test.ts", "7.8"],
  ["OBJ-PUB-002", "object", "src/state/publication.test.ts", "7.8"],
  ["OBJ-FLOW-001", "object", "e2e/s3-http-pipeline.test.ts", "7.9"],
  ["OBJ-FLOW-002", "object", "e2e/object-store-flow.test.ts", "7.9"],
  ["OBJ-FLOW-003", "object", "e2e/object-store-flow.test.ts", "7.9"],
  ["OBJ-FLOW-004", "object", "src/s3/publisher.test.ts", null],
  ["OBJ-FLOW-005", "object", "src/s3/http.test.ts", null],
  ["OBJ-FLOW-006", "object", "src/s3/publisher.test.ts", null],
  ["OBJ-FLOW-007", "object", "src/s3/publisher.test.ts", null],
  ["OBJ-FLOW-008", "object", "src/s3/http.test.ts", null],
  ["OBJ-FLOW-009", "object", "src/s3/publisher.test.ts", null],
  ["OBJ-FLOW-010", "object", "src/s3/http.test.ts", null],
  ["OBJ-FLOW-011", "object", "e2e/runtime-pipeline.test.ts", null],
  ["OBJ-FLOW-012", "object", "src/s3/publisher.test.ts", null],
  ["OBJ-FLOW-013", "object", "e2e/s3-http-pipeline.test.ts", null],
  ["OBJ-RUNTIME-001", "object", "src/s3/http.test.ts", "6.6"],
  ["OBJ-RUNTIME-002", "object", "src/s3/http.test.ts", "6.6"],
  ["OBJ-RUNTIME-003", "object", "src/s3/http.test.ts", "6.6"],
  ["OBJ-RUNTIME-004", "object", "src/s3/http.test.ts", "6.6"],
  ["OBJ-RUNTIME-005", "object", "src/s3/http.test.ts", "6.6"],
  ["OBJ-RUNTIME-006", "object", "src/s3/http.test.ts", "6.6"],
  ["OBJ-RUNTIME-007", "object", "src/s3/http.test.ts", "6.6"],
  ["OBJ-RUNTIME-008", "object", "e2e/s3-http-pipeline.test.ts", null],
  ["OBJ-RUNTIME-009", "object", "e2e/s3-http-pipeline.test.ts", null],
  ["OBJ-RUNTIME-010", "object", "src/s3/http.test.ts", "6.6"],
  ["OBJ-RUNTIME-011", "object", "src/s3/http.test.ts", "6.6"],
  ["OBJ-RUNTIME-012", "object", "src/s3/http.test.ts", "6.6"],
  ["OBJ-RUNTIME-013", "object", "src/s3/http.test.ts", "6.6"],
  ["OBJ-RUNTIME-014", "object", "e2e/s3-http-pipeline.test.ts", null],
  ["OBJ-CACHE-001", "object", "src/state/cache-policy.test.ts", "10.4"],
  [
    "OBJ-CACHE-002",
    "object",
    "src/state/direct-public-security-policy.test.ts",
    "10.4",
  ],
  ["OBJ-CACHE-003", "object", "src/state/cache-policy.test.ts", "10.4"],
  [
    "OBJ-CACHE-004",
    "object",
    "src/state/direct-public-security-policy.test.ts",
    "10.4",
  ],
  [
    "OBJ-CACHE-005",
    "object",
    "src/state/direct-public-security-policy.test.ts",
    "10.4",
  ],
  ["HLS-GOLDEN-001", "hls", "src/hls/master-playlist.test.ts", "8.2"],
  ["HLS-GOLDEN-002", "hls", "src/hls/media-playlist.test.ts", "8.4"],
  ["HLS-GOLDEN-003", "hls", "src/hls/media-playlist.test.ts", "8.4"],
  ["HLS-GOLDEN-004", "hls", "src/hls/media-playlist.test.ts", "8.4"],
  ["HLS-GOLDEN-005", "hls", "src/hls/media-playlist.test.ts", "8.4"],
  ["HLS-GOLDEN-006", "hls", "src/hls/media-playlist.test.ts", "8.4"],
  ["HLS-GOLDEN-007", "hls", "src/hls/media-playlist.test.ts", "8.4"],
  ["HLS-GOLDEN-008", "hls", "src/hls/media-playlist.test.ts", "8.4"],
  ["HLS-GOLDEN-009", "hls", "src/hls/master-playlist.test.ts", "8.2"],
  ["HLS-GOLDEN-010", "hls", "src/hls/media-playlist.test.ts", "8.4"],
  ["HLS-GOLDEN-011", "hls", "src/hls/media-playlist.test.ts", "8.4"],
  ["HLS-ENDLIST-001", "hls", "src/hls/manifest-artifacts.test.ts", "8.6"],
  ["HLS-HOLDBACK-001", "hls", "src/hls/media-playlist.test.ts", "8.4.1"],
  ["HLS-BLOCK-001", "hls", "src/hls/blocking-reload.test.ts", "8.7"],
  ["HLS-BLOCK-002", "hls", "src/hls/manifest-artifacts.test.ts", "8.7"],
  ["HLS-BLOCK-003", "hls", "e2e/runtime-client-flow.test.ts", "8.7"],
  ["HLS-BYTERANGE-001", "hls", "src/validation/byterange.test.ts", "8.5"],
  ["HLS-BYTERANGE-002", "hls", "src/hls/media-playlist.test.ts", "8.5"],
  ["HLS-BYTERANGE-003", "hls", "src/hls/media-playlist.test.ts", "8.5"],
  ["HLS-AUDIO-001", "hls", "src/hls/master-playlist.test.ts", "8.3"],
  ["HLS-AUDIO-002", "hls", "src/hls/master-playlist.test.ts", "8.3"],
  ["HLS-AVAIL-001", "hls", "src/hls/manifest-artifacts.test.ts", "8.2"],
  ["SEC-DIRECT-004", "security", "src/s3/http.test.ts", "10.3"],
  [
    "SEC-DIRECT-001",
    "security",
    "src/state/direct-public-security-policy.test.ts",
    "10.2",
  ],
  ["SEC-DIRECT-002", "security", "src/validation/upload-slot.test.ts", "10.5"],
  ["SEC-DIRECT-003", "security", "src/s3/http.test.ts", "10.3"],
  ["SEC-DIRECT-005", "security", "src/validation/upload-slot.test.ts", "10.5"],
  ["SEC-DIRECT-006", "security", "src/s3/http.test.ts", "10.3"],
  ["SEC-DIRECT-007", "security", "src/s3/http.test.ts", "10.3"],
] as const satisfies readonly OlosConformanceCoverageRow[];

/** Identifier of one assertion in the OLOS conformance suite. */
export type OlosConformanceAssertionId =
  (typeof OLOS_CONFORMANCE_COVERAGE_ROWS)[number][0];

/** Every assertion id defined by the OLOS conformance suite. */
export const OLOS_CONFORMANCE_ASSERTION_IDS: readonly OlosConformanceAssertionId[] =
  OLOS_CONFORMANCE_COVERAGE_ROWS.map((row) => row[0]);
