import type { OlosConformanceAssertionId } from "./assertion-ids";
import type {
  OlosConformanceCoverageStatus,
  OlosConformanceLevel,
} from "./metadata";

export type OlosConformanceCoverageRow = readonly [
  OlosConformanceAssertionId,
  OlosConformanceLevel,
  string,
  OlosConformanceCoverageStatus?,
];

export const OLOS_CONFORMANCE_COVERAGE_ROWS = [
  ["CORE-STORE-001", "core", "src/conformance.test.ts"],
  ["CORE-STORE-002", "core", "src/conformance.test.ts"],
  ["CORE-STORE-003", "core", "src/conformance.test.ts"],
  ["CORE-STORE-004", "core", "src/conformance.test.ts"],
  ["CORE-STORE-005", "core", "src/conformance.test.ts"],
  ["CORE-STORE-006", "core", "src/protocol/serialized-store.test.ts"],
  ["CORE-STORE-007", "core", "src/protocol/serialized-store.test.ts"],
  ["CORE-STORE-008", "core", "src/protocol/sqlite-store.test.ts"],
  ["CORE-SCHEMA-001", "core", "src/schema.test.ts"],
  ["CORE-SLOT-001", "core", "src/state/upload-slot.test.ts"],
  ["CORE-SLOT-002", "core", "src/state/upload-slot.test.ts"],
  ["CORE-SLOT-003", "core", "src/state/commit.test.ts"],
  ["CORE-SLOT-004", "core", "src/state/upload-slot.test.ts"],
  ["CORE-SLOT-005", "core", "src/state/upload-slot.test.ts"],
  ["CORE-SLOT-006", "core", "src/protocol/coordinator.test.ts"],
  ["CORE-SLOT-007", "core", "src/protocol/coordinator.test.ts"],
  ["CORE-COMMIT-001", "core", "src/state/commit.test.ts"],
  ["CORE-COMMIT-002", "core", "src/state/commit.test.ts"],
  ["CORE-COMMIT-003", "core", "src/state/commit.test.ts"],
  ["CORE-COMMIT-004", "core", "src/state/commit.test.ts"],
  ["CORE-COMMIT-005", "core", "src/state/commit.test.ts"],
  ["CORE-COMMIT-006", "core", "src/state/commit.test.ts"],
  ["CORE-COMMIT-007", "core", "src/state/commit.test.ts"],
  ["CORE-COMMIT-008", "core", "src/state/committed-window.test.ts"],
  ["CORE-LATE-001", "core", "src/state/commit.test.ts"],
  ["CORE-LATE-002", "core", "src/state/commit.test.ts"],
  ["CORE-EVENT-001", "core", "src/state/observed-upload.test.ts"],
  ["CORE-EVENT-002", "core", "src/state/observed-upload.test.ts"],
  ["CORE-EVENT-003", "core", "src/state/observed-upload.test.ts"],
  ["CORE-EVENT-004", "core", "src/state/observed-upload.test.ts"],
  ["CORE-EVENT-005", "core", "src/state/observed-upload.test.ts"],
  ["CORE-WINDOW-001", "core", "src/state/cursor.test.ts"],
  ["CORE-WINDOW-002", "core", "src/hls/media-playlist.test.ts"],
  ["CORE-WINDOW-003", "core", "src/validation/committed-window.test.ts"],
  ["CORE-WINDOW-004", "core", "src/validation/committed-window.test.ts"],
  ["CORE-WINDOW-005", "core", "src/validation/committed-window.test.ts"],
  ["CORE-WINDOW-006", "core", "src/hls/media-playlist.test.ts"],
  ["CORE-WINDOW-007", "core", "src/state/committed-window.test.ts"],
  ["CORE-RUNTIME-001", "core", "e2e/runtime-pipeline.test.ts"],
  ["CORE-RUNTIME-002", "core", "e2e/runtime-pipeline.test.ts"],
  ["CORE-RUNTIME-003", "core", "e2e/runtime-pipeline.test.ts"],
  ["CORE-RUNTIME-004", "core", "src/runtime/http.test.ts"],
  ["CORE-RUNTIME-005", "core", "src/runtime/http.test.ts"],
  ["CORE-RUNTIME-006", "core", "src/runtime/retention.test.ts"],
  ["CORE-RUNTIME-007", "core", "src/runtime/publisher.test.ts"],
  ["CORE-RUNTIME-008", "core", "src/runtime/publisher-lease.test.ts"],
  ["CORE-RUNTIME-009", "core", "src/runtime/publisher-plan.test.ts"],
  ["CORE-RUNTIME-010", "core", "src/runtime/publisher-expiry.test.ts"],
  ["CORE-RUNTIME-011", "core", "src/runtime/health.test.ts"],
  ["CORE-RUNTIME-012", "core", "src/runtime/latency-profile.test.ts"],
  ["CORE-RUNTIME-013", "core", "src/runtime/publisher-cadence.test.ts"],
  ["CORE-RUNTIME-014", "core", "src/runtime/publisher-cadence.test.ts"],
  ["CORE-RUNTIME-015", "core", "src/runtime/publisher.test.ts"],
  ["CORE-RUNTIME-016", "core", "src/runtime/session.test.ts"],
  ["CORE-RUNTIME-017", "core", "src/runtime/http.test.ts"],
  ["CORE-RUNTIME-018", "core", "src/runtime/client.test.ts"],
  ["CORE-RUNTIME-019", "core", "e2e/runtime-client-flow.test.ts"],
  ["CORE-RUNTIME-020", "core", "src/runtime/slot.test.ts"],
  ["CORE-RUNTIME-021", "core", "src/runtime/commit.test.ts"],
  ["CORE-RUNTIME-022", "core", "src/runtime/http.test.ts"],
  ["CORE-RUNTIME-023", "core", "src/runtime/http.test.ts"],
  ["CORE-RUNTIME-024", "core", "src/runtime/http.test.ts"],
  ["OBJ-LAYOUT-001", "object", "src/runtime/publisher-plan.test.ts"],
  ["OBJ-GRANT-001", "object", "src/s3/upload-grant.test.ts"],
  ["OBJ-GRANT-002", "object", "src/s3/upload-grant.test.ts"],
  ["OBJ-GRANT-003", "object", "src/s3/coordinator.test.ts"],
  ["OBJ-GRANT-004", "object", "src/state/provider-upload-grant-policy.test.ts"],
  ["OBJ-GRANT-005", "object", "src/state/provider-upload-grant-policy.test.ts"],
  ["OBJ-HEAD-001", "object", "src/state/observed-upload.test.ts"],
  ["OBJ-PUB-001", "object", "src/state/publication.test.ts"],
  ["OBJ-PUB-002", "object", "src/state/publication.test.ts"],
  ["OBJ-FLOW-001", "object", "e2e/s3-http-pipeline.test.ts"],
  ["OBJ-FLOW-002", "object", "e2e/object-store-flow.test.ts"],
  ["OBJ-FLOW-003", "object", "e2e/object-store-flow.test.ts"],
  ["OBJ-FLOW-004", "object", "src/s3/publisher.test.ts"],
  ["OBJ-FLOW-005", "object", "src/s3/http.test.ts"],
  ["OBJ-FLOW-006", "object", "src/s3/publisher.test.ts"],
  ["OBJ-FLOW-007", "object", "src/s3/publisher.test.ts"],
  ["OBJ-FLOW-008", "object", "src/s3/http.test.ts"],
  ["OBJ-FLOW-009", "object", "src/s3/publisher.test.ts"],
  ["OBJ-FLOW-010", "object", "src/s3/http.test.ts"],
  ["OBJ-FLOW-011", "object", "e2e/runtime-pipeline.test.ts"],
  ["OBJ-FLOW-012", "object", "src/s3/publisher.test.ts"],
  ["OBJ-FLOW-013", "object", "e2e/s3-http-pipeline.test.ts"],
  ["OBJ-RUNTIME-001", "object", "src/s3/http.test.ts"],
  ["OBJ-RUNTIME-002", "object", "src/s3/http.test.ts"],
  ["OBJ-RUNTIME-003", "object", "src/s3/http.test.ts"],
  ["OBJ-RUNTIME-004", "object", "src/s3/http.test.ts"],
  ["OBJ-RUNTIME-005", "object", "src/s3/http.test.ts"],
  ["OBJ-RUNTIME-006", "object", "src/s3/http.test.ts"],
  ["OBJ-RUNTIME-007", "object", "src/s3/http.test.ts"],
  ["OBJ-RUNTIME-008", "object", "e2e/s3-http-pipeline.test.ts"],
  ["OBJ-RUNTIME-009", "object", "e2e/s3-http-pipeline.test.ts"],
  ["OBJ-RUNTIME-010", "object", "src/s3/http.test.ts"],
  ["OBJ-RUNTIME-011", "object", "src/s3/http.test.ts"],
  ["OBJ-RUNTIME-012", "object", "src/s3/http.test.ts"],
  ["OBJ-RUNTIME-013", "object", "src/s3/http.test.ts"],
  ["OBJ-RUNTIME-014", "object", "e2e/s3-http-pipeline.test.ts"],
  ["OBJ-CACHE-001", "object", "src/state/cache-policy.test.ts"],
  [
    "OBJ-CACHE-002",
    "object",
    "src/state/direct-public-security-policy.test.ts",
  ],
  ["OBJ-CACHE-003", "object", "src/state/cache-policy.test.ts"],
  [
    "OBJ-CACHE-004",
    "object",
    "src/state/direct-public-security-policy.test.ts",
  ],
  [
    "OBJ-CACHE-005",
    "object",
    "src/state/direct-public-security-policy.test.ts",
  ],
  ["HLS-GOLDEN-001", "hls", "src/hls/master-playlist.test.ts"],
  ["HLS-GOLDEN-002", "hls", "src/hls/media-playlist.test.ts"],
  ["HLS-GOLDEN-003", "hls", "src/hls/media-playlist.test.ts"],
  ["HLS-GOLDEN-004", "hls", "src/hls/media-playlist.test.ts"],
  ["HLS-GOLDEN-005", "hls", "src/hls/media-playlist.test.ts"],
  ["HLS-GOLDEN-006", "hls", "src/hls/media-playlist.test.ts"],
  ["HLS-GOLDEN-007", "hls", "src/hls/media-playlist.test.ts"],
  ["HLS-GOLDEN-008", "hls", "src/hls/media-playlist.test.ts"],
  ["HLS-GOLDEN-009", "hls", "src/hls/master-playlist.test.ts"],
  ["HLS-GOLDEN-010", "hls", "src/hls/media-playlist.test.ts"],
  ["HLS-HOLDBACK-001", "hls", "src/hls/media-playlist.test.ts"],
  ["HLS-BLOCK-001", "hls", "src/hls/blocking-reload.test.ts"],
  ["HLS-BLOCK-002", "hls", "src/hls/manifest-artifacts.test.ts"],
  ["HLS-BLOCK-003", "hls", "e2e/runtime-client-flow.test.ts"],
  ["HLS-BYTERANGE-001", "hls", "src/validation/byterange.test.ts"],
  ["HLS-BYTERANGE-002", "hls", "src/hls/media-playlist.test.ts"],
  ["HLS-BYTERANGE-003", "hls", "src/hls/media-playlist.test.ts"],
  ["SEC-DIRECT-004", "security", "src/s3/http.test.ts"],
  [
    "SEC-DIRECT-001",
    "security",
    "src/state/direct-public-security-policy.test.ts",
  ],
  ["SEC-DIRECT-002", "security", "src/validation/upload-slot.test.ts"],
  ["SEC-DIRECT-003", "security", "src/s3/http.test.ts"],
  ["SEC-DIRECT-005", "security", "src/validation/upload-slot.test.ts"],
  ["SEC-DIRECT-006", "security", "src/s3/http.test.ts"],
  ["SEC-DIRECT-007", "security", "src/s3/http.test.ts"],
] as const satisfies readonly OlosConformanceCoverageRow[];
