export const OLOS_ERROR_CODES = [
  "olos.invalid_session",
  "olos.invalid_state",
  "olos.unknown_slot",
  "olos.slot_expired",
  "olos.key_mismatch",
  "olos.content_type_mismatch",
  "olos.object_too_large",
  "olos.object_too_small",
  "olos.duplicate_commit_conflict",
  "olos.cursor_regression",
  "olos.provider_unavailable",
  "olos.quota_exceeded",
  "olos.security_policy_violation",
] as const;
