/* Public package surface expected by export-map, README, and smoke tests. */
export const expectedRuntimeExports = {
  "@arsenstorm/olos": [
    "OLOS_PROTOCOL_NAME",
    "OLOS_PROTOCOL_SHORT_NAME",
    "OLOS_SPEC_STATUS",
    "OLOS_WIRE_VERSION",
  ],
  "@arsenstorm/olos/config": [
    "OLOS_ERROR_CODES",
    "SESSION_STATES",
    "UPLOAD_SLOT_STATES",
  ],
  "@arsenstorm/olos/conformance": [
    "OLOS_CONFORMANCE_ASSERTION_IDS",
    "OLOS_CONFORMANCE_COVERAGE",
  ],
  "@arsenstorm/olos/hls": [
    "createHlsManifestArtifactResponse",
    "createHlsManifestErrorWebResponse",
    "createHlsManifestWebResponse",
    "parseHlsBlockingReloadRequest",
    "renderMediaPlaylist",
    "resolveBlockingHlsManifestArtifactResponse",
    "resolveHlsBlockingReload",
    "resolveHlsManifestArtifactResponse",
    "waitForHlsBlockingReload",
  ],
  "@arsenstorm/olos/protocol": [
    "assertSerializedCoordinatorStoreBackendConformance",
    "createCoordinatorPipeline",
    "createMemoryCoordinatorStore",
    "createMemorySerializedCoordinatorStoreBackend",
    "createNextCoordinatorPipelineEtag",
    "createSerializedCoordinatorStore",
    "createSqliteSerializedCoordinatorStoreBackend",
    "createSqliteSerializedCoordinatorStoreSchema",
    "parseCoordinatorPipelineSnapshot",
    "planCoordinatorRetention",
    "serializeCoordinatorPipelineSnapshot",
  ],
  "@arsenstorm/olos/runtime": [
    "commitStoredCoordinatorUploadFromRequest",
    "commitRuntimeUpload",
    "createMemoryRuntimeCursorNotifier",
    "createRuntimeObjectLowLatencyManifestOptions",
    "createRuntimeObjectLowLatencyProfile",
    "createRuntimeObjectLowLatencyPublisherDefaults",
    "createRuntimeObjectLowLatencyPublisherOptions",
    "createRuntimePublisherLease",
    "createRuntimePublisherNextObjectPlan",
    "createRuntimePublisherObjectKeyNonce",
    "createRuntimePublisherObjectPlan",
    "createRuntimePublisherObjectPlanInput",
    "createRuntimeSession",
    "createStoredCoordinatorSession",
    "createStoredCoordinatorRuntimeHandler",
    "deleteRetiredCoordinatorObjects",
    "getRuntimeMasterPlaylist",
    "getRuntimeMediaPlaylist",
    "getRuntimeSessionHealth",
    "getRuntimeSessionRetentionPlan",
    "issueStoredCoordinatorSlotFromRequest",
    "issueRuntimeSlot",
    "planStoredCoordinatorRetention",
    "resolveRuntimeLiveHealth",
    "resolveRuntimePublisherLeaseStatus",
    "resolveRuntimePublisherLoopDecision",
    "resolveRuntimePublisherNextObjectPosition",
    "resolveRuntimePublisherObjectExpiry",
    "refreshRuntimePublisherLease",
    "runRuntimePublisherUploadStep",
    "RuntimeHttpError",
    "sendRuntimePublisherHeartbeat",
    "serveStoredBlockingCoordinatorManifest",
    "serveStoredCoordinatorManifest",
    "summarizeRetiredCoordinatorObjectDeletions",
    "transitionStoredCoordinatorSession",
    "transitionRuntimeSession",
  ],
  "@arsenstorm/olos/schema": [
    "OLOS_COMMIT_SCHEMA",
    "OLOS_CURSOR_SCHEMA",
    "OLOS_ERROR_SCHEMA",
    "OLOS_JSON_SCHEMAS",
    "OLOS_MEDIA_OBJECT_SCHEMA",
    "OLOS_PROVIDER_CAPABILITY_SCHEMA",
    "OLOS_SESSION_SCHEMA",
    "OLOS_UPLOAD_GRANT_SCHEMA",
    "OLOS_UPLOAD_SLOT_SCHEMA",
  ],
  "@arsenstorm/olos/s3": [
    "applyS3RuntimeRetention",
    "completeS3RuntimeUpload",
    "commitS3RuntimeUpload",
    "createPresignedS3UploadGrant",
    "createS3UploadGrant",
    "createObservedUploadFromS3HeadObject",
    "createStoredS3CoordinatorRuntimeHandler",
    "deleteRetiredS3CoordinatorObjects",
    "issueS3RuntimeUploadGrant",
    "issueStoredS3CoordinatorUploadGrant",
    "normalizeS3ObjectCreatedEvents",
    "observeS3Object",
    "planS3RuntimeReconciliation",
    "planStoredS3CoordinatorReconciliation",
    "reconcileS3RuntimeUploads",
    "reconcileStoredS3CoordinatorUploads",
    "routeStoredS3CoordinatorUploadEvent",
    "runNextStoredS3PublisherUploadStep",
    "runPlannedStoredS3PublisherUploadStep",
    "runStoredS3PublisherUploadStep",
    "summarizeStoredS3CoordinatorUploadReconciliation",
    "summarizeStoredS3PublisherUploadStep",
  ],
  "@arsenstorm/olos/state": [
    "createCursor",
    "createDirectPublicMediaResponseHeaders",
    "createDirectPublicNegativeObjectResponseHeaders",
    "createDirectPublicSecurityPolicy",
    "createPublicationKillSwitch",
    "resolveDirectPublicMediaRequestPolicy",
    "resolvePublicationControl",
    "selectExpiredUploadSlots",
    "selectRetiredCommittedObjects",
  ],
  "@arsenstorm/olos/types": [],
  "@arsenstorm/olos/validation": ["assertSession", "isSession", "isUploadSlot"],
} as const;
